### ISSUE TITLE
MongoDB Integration

### ISSUE THREAD

**Issue by aszrul** [emiliano-viada-developer/HasheadoAdminBundle#1]
Hi,

So far this bundle integrates very well for Doctrine ORM, however, when I tried to configure it to use MongoDB, I came across with this error,

```
[Symfony\Component\Config\Definition\Exception\ForbiddenOverwriteException]
Configuration path "fos_user.db_driver" cannot be overwritten. You have to define all options for this path, and any of its sub-paths i
n one configuration section.
```

For your information, I did added MongoDB Admin Bundle and Doctrine MongoDB Bundle in order to apply MongoDB into the system. I'm also did every necessary configurations as well.

What I dont get it when I tried every options on fos_user inside config, whether I added all options or not, above error message keep appeared.

Is this the bug from FOSUserBundle itself?

**Comment by emiviada** [comment]
@aszrul the problem is that this bundle is already configured to just use ORM as you can see in https://github.com/emiliano-viada-developer/HasheadoAdminBundle/blob/master/Resources/config/config.yml line 46. So, when you try to override this, FOSUserBundle does not allow you.

I will fix this as soon as possible (maybe tonight) and I'll let you know.

**Comment by aszrul** [comment]
I see, thank you very much. I hope you can make it customizable. :)

**Comment by emiviada** [comment]
@aszrul I've moved the fos_user config out from the bundle so it's up to your config file now. Please, let me know if this works, thanks.

**Comment by aszrul** [comment]
Just FYI, it was working fine. Thanks 👍
